# @generated by scripts/codegen.py -- DO NOT EDIT.
# Regenerate: python scripts/codegen.py
"""Generated Closebot endpoint modules -- one per API tag.

Each submodule exposes module-level functions (one per operation) that take a
:class:`~closewire_client.rest.RestClient`. Operation identity/naming comes from
the vendored ``schema/endpoints.index.json``; see ``OPERATIONS.md`` for the full
index. The runtime live-message op lives in :mod:`closewire_client.live`.
"""

from closewire_client.endpoints import account as account
from closewire_client.endpoints import agency as agency
from closewire_client.endpoints import billing as billing
from closewire_client.endpoints import bot as bot
from closewire_client.endpoints import bot_metric as bot_metric
from closewire_client.endpoints import bot_source_variable as bot_source_variable
from closewire_client.endpoints import bot_template as bot_template
from closewire_client.endpoints import bot_testing as bot_testing
from closewire_client.endpoints import hierarchy as hierarchy
from closewire_client.endpoints import lead as lead
from closewire_client.endpoints import library as library
from closewire_client.endpoints import live_demo as live_demo
from closewire_client.endpoints import notification as notification
from closewire_client.endpoints import persona as persona
from closewire_client.endpoints import smart_faq as smart_faq
from closewire_client.endpoints import source as source
from closewire_client.endpoints import webhook as webhook

MODULES = [
    "account",
    "agency",
    "billing",
    "bot",
    "bot_metric",
    "bot_source_variable",
    "bot_template",
    "bot_testing",
    "hierarchy",
    "lead",
    "library",
    "live_demo",
    "notification",
    "persona",
    "smart_faq",
    "source",
    "webhook",
]

__all__ = list(MODULES)
