# @generated by scripts/codegen.py -- DO NOT EDIT.
# Source: schema/endpoints.index.json + schema/openapi.json
#         (vendored from Bleupreneur/closebot-agency-toolkit, MIT).
# Regenerate: python scripts/codegen.py
"""Account endpoints -- generated Closebot operations.

Tag: Account. 3 operation(s). Each function takes a
:class:`~closewire_client.rest.RestClient` as its first argument and delegates
to :meth:`RestClient.request` -- the single paced, authenticated call-site.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover - typing only
    from closewire_client.rest import RestClient

__all__ = [
    "get_account_apikey",
    "post_account_apikey",
    "delete_account_apikey_keyid",
]


def get_account_apikey(client: RestClient) -> Any:
    """List API keys

    ``GET /account/apiKey``  |  tag: Account

    Body: (none)
    Auth: X-CB-KEY  |  Response: ApiKeyDTO
    """
    return client.request("GET", "/account/apiKey")


def post_account_apikey(client: RestClient, *, body: dict[str, Any] | None = None) -> Any:
    """Create API Key

    ``POST /account/apiKey``  |  tag: Account

    Body: CreateApiKeyInput
    Auth: X-CB-KEY  |  Response: CreateApiKeyOutput
    """
    return client.request("POST", "/account/apiKey", json=body)


def delete_account_apikey_keyid(client: RestClient, keyId: str) -> Any:
    """Delete API Key

    ``DELETE /account/apiKey/{keyId}``  |  tag: Account

    Path params:
      - ``keyId``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/account/apiKey/{keyId}".format(**{"keyId": keyId})
    return client.request("DELETE", path)
