# @generated by scripts/codegen.py -- DO NOT EDIT.
# Source: schema/endpoints.index.json + schema/openapi.json
#         (vendored from Bleupreneur/closebot-agency-toolkit, MIT).
# Regenerate: python scripts/codegen.py
"""Agency endpoints -- generated Closebot operations.

Tag: Agency. 5 operation(s). Each function takes a
:class:`~closewire_client.rest.RestClient` as its first argument and delegates
to :meth:`RestClient.request` -- the single paced, authenticated call-site.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover - typing only
    from closewire_client.rest import RestClient

__all__ = [
    "get_agency",
    "get_agency_current",
    "delete_agency_invite",
    "post_agency_invite",
    "get_agency_usage",
]


def get_agency(client: RestClient) -> Any:
    """List agencies

    ``GET /agency``  |  tag: Agency

    Body: (none)
    Auth: X-CB-KEY  |  Response: AgencyDto
    """
    return client.request("GET", "/agency")


def get_agency_current(client: RestClient) -> Any:
    """Get agency

    ``GET /agency/current``  |  tag: Agency

    Body: (none)
    Auth: X-CB-KEY  |  Response: AgencyDto
    """
    return client.request("GET", "/agency/current")


def delete_agency_invite(client: RestClient, *, email: str | None = None) -> Any:
    """Revoke invitation

    ``DELETE /agency/invite``  |  tag: Agency

    Query params:
      - ``email``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    params = {k: v for k, v in {"email": email}.items() if v is not None}
    return client.request("DELETE", "/agency/invite", params=params)


def post_agency_invite(client: RestClient, *, body: dict[str, Any] | None = None) -> Any:
    """Invite users

    ``POST /agency/invite``  |  tag: Agency

    Body: InviteUserInput
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    return client.request("POST", "/agency/invite", json=body)


def get_agency_usage(client: RestClient, *, scopes: str | None = None) -> Any:
    """Get usage

    ``GET /agency/usage``  |  tag: Agency

    Query params:
      - ``scopes``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    params = {k: v for k, v in {"scopes": scopes}.items() if v is not None}
    return client.request("GET", "/agency/usage", params=params)
