# @generated by scripts/codegen.py -- DO NOT EDIT.
# Source: schema/endpoints.index.json + schema/openapi.json
#         (vendored from Bleupreneur/closebot-agency-toolkit, MIT).
# Regenerate: python scripts/codegen.py
"""Billing endpoints -- generated Closebot operations.

Tag: Billing. 13 operation(s). Each function takes a
:class:`~closewire_client.rest.RestClient` as its first argument and delegates
to :meth:`RestClient.request` -- the single paced, authenticated call-site.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover - typing only
    from closewire_client.rest import RestClient

__all__ = [
    "get_agency_billing_balance",
    "get_agency_billing_balance_source_sourceid",
    "get_agency_billing_options",
    "put_agency_billing_options",
    "get_agency_billing_re_billing",
    "put_agency_billing_re_billing",
    "post_agency_billing_refill",
    "post_agency_billing_refill_source_sourceid",
    "get_agency_billing_transactions",
    "get_agency_billing_transactions_source_sourceid",
    "post_agency_billing_transactions_source_sourceid",
    "delete_agency_billing_transactions_source_sourceid_id",
    "get_agency_billing_usages",
]


def get_agency_billing_balance(client: RestClient) -> Any:
    """Get agency balance

    ``GET /agency/billing/balance``  |  tag: Billing

    Body: (none)
    Auth: X-CB-KEY  |  Response: BalanceDto
    """
    return client.request("GET", "/agency/billing/balance")


def get_agency_billing_balance_source_sourceid(client: RestClient, sourceId: str) -> Any:
    """Get source balance

    ``GET /agency/billing/balance/source/{sourceId}``  |  tag: Billing

    Path params:
      - ``sourceId``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: BalanceDto
    """
    path = "/agency/billing/balance/source/{sourceId}".format(**{"sourceId": sourceId})
    return client.request("GET", path)


def get_agency_billing_options(client: RestClient) -> Any:
    """Get agency billing

    ``GET /agency/billing/options``  |  tag: Billing

    Body: (none)
    Auth: X-CB-KEY  |  Response: BillingOptionsDto
    """
    return client.request("GET", "/agency/billing/options")


def put_agency_billing_options(
    client: RestClient,
    *,
    body: dict[str, Any] | None = None,
) -> Any:
    """Update agency billing

    ``PUT /agency/billing/options``  |  tag: Billing

    Body: UpdateBillingConfigInput
    Auth: X-CB-KEY  |  Response: BillingOptionsDto
    """
    return client.request("PUT", "/agency/billing/options", json=body)


def get_agency_billing_re_billing(client: RestClient) -> Any:
    """Get re-billing settings

    ``GET /agency/billing/re-billing``  |  tag: Billing

    Body: (none)
    Auth: X-CB-KEY  |  Response: ReBillingDto
    """
    return client.request("GET", "/agency/billing/re-billing")


def put_agency_billing_re_billing(
    client: RestClient,
    *,
    body: dict[str, Any] | None = None,
) -> Any:
    """Update re-billing

    ``PUT /agency/billing/re-billing``  |  tag: Billing

    Body: ReBillingUpdateInput
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    return client.request("PUT", "/agency/billing/re-billing", json=body)


def post_agency_billing_refill(
    client: RestClient,
    *,
    body: dict[str, Any] | None = None,
) -> Any:
    """Refill agency wallet

    ``POST /agency/billing/refill``  |  tag: Billing

    Body: CreateRefillDto
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    return client.request("POST", "/agency/billing/refill", json=body)


def post_agency_billing_refill_source_sourceid(
    client: RestClient,
    sourceId: str,
    *,
    body: dict[str, Any] | None = None,
) -> Any:
    """Refill source wallet

    ``POST /agency/billing/refill/source/{sourceId}``  |  tag: Billing

    Path params:
      - ``sourceId``: str
    Body: CreateRefillDto
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/agency/billing/refill/source/{sourceId}".format(**{"sourceId": sourceId})
    return client.request("POST", path, json=body)


def get_agency_billing_transactions(
    client: RestClient,
    *,
    status: str | None = None,
    page: int | None = None,
    pageSize: int | None = None,
) -> Any:
    """List agency transactions

    ``GET /agency/billing/transactions``  |  tag: Billing

    Query params:
      - ``status``: str
      - ``page``: int
      - ``pageSize``: int
    Body: (none)
    Auth: X-CB-KEY  |  Response: TransactionDto
    """
    params = {k: v for k, v in {"status": status, "page": page, "pageSize": pageSize}.items() if v is not None}
    return client.request("GET", "/agency/billing/transactions", params=params)


def get_agency_billing_transactions_source_sourceid(
    client: RestClient,
    sourceId: str,
    *,
    status: str | None = None,
    page: int | None = None,
    pageSize: int | None = None,
) -> Any:
    """List source transactions

    ``GET /agency/billing/transactions/source/{sourceId}``  |  tag: Billing

    Path params:
      - ``sourceId``: str
    Query params:
      - ``status``: str
      - ``page``: int
      - ``pageSize``: int
    Body: (none)
    Auth: X-CB-KEY  |  Response: TransactionDto
    """
    path = "/agency/billing/transactions/source/{sourceId}".format(**{"sourceId": sourceId})
    params = {k: v for k, v in {"status": status, "page": page, "pageSize": pageSize}.items() if v is not None}
    return client.request("GET", path, params=params)


def post_agency_billing_transactions_source_sourceid(
    client: RestClient,
    sourceId: str,
    *,
    body: dict[str, Any] | None = None,
) -> Any:
    """Add source transaction

    ``POST /agency/billing/transactions/source/{sourceId}``  |  tag: Billing

    Path params:
      - ``sourceId``: str
    Body: AddSourceTransactionDto
    Auth: X-CB-KEY  |  Response: TransactionDto
    """
    path = "/agency/billing/transactions/source/{sourceId}".format(**{"sourceId": sourceId})
    return client.request("POST", path, json=body)


def delete_agency_billing_transactions_source_sourceid_id(
    client: RestClient,
    sourceId: str,
    id: int,
) -> Any:
    """Delete source transaction

    ``DELETE /agency/billing/transactions/source/{sourceId}/{id}``  |  tag: Billing

    Path params:
      - ``sourceId``: str
      - ``id``: int
    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/agency/billing/transactions/source/{sourceId}/{id}".format(**{"sourceId": sourceId, "id": id})
    return client.request("DELETE", path)


def get_agency_billing_usages(
    client: RestClient,
    *,
    startTime: str | None = None,
    endTime: str | None = None,
) -> Any:
    """List billed usages

    ``GET /agency/billing/usages``  |  tag: Billing

    Query params:
      - ``startTime``: str
      - ``endTime``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: BilledUsageDto
    """
    params = {k: v for k, v in {"startTime": startTime, "endTime": endTime}.items() if v is not None}
    return client.request("GET", "/agency/billing/usages", params=params)
