# @generated by scripts/codegen.py -- DO NOT EDIT.
# Source: schema/endpoints.index.json + schema/openapi.json
#         (vendored from Bleupreneur/closebot-agency-toolkit, MIT).
# Regenerate: python scripts/codegen.py
"""Bot endpoints -- generated Closebot operations.

Tag: Bot. 17 operation(s). Each function takes a
:class:`~closewire_client.rest.RestClient` as its first argument and delegates
to :meth:`RestClient.request` -- the single paced, authenticated call-site.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover - typing only
    from closewire_client.rest import RestClient

__all__ = [
    "get_bot",
    "post_bot",
    "post_bot_ai",
    "get_bot_bbb_templates",
    "get_bot_nodedescriptors",
    "delete_bot_id",
    "get_bot_id",
    "put_bot_id",
    "post_bot_id_duplicate",
    "get_bot_id_export",
    "post_bot_id_publish",
    "post_bot_id_save",
    "post_bot_id_savetools",
    "delete_bot_id_source_sourceid",
    "post_bot_id_source_sourceid",
    "get_bot_id_steps",
    "put_bot_id_version_version",
]


def get_bot(client: RestClient) -> Any:
    """List bots

    ``GET /bot``  |  tag: Bot

    Body: (none)
    Auth: X-CB-KEY  |  Response: BotDto
    """
    return client.request("GET", "/bot")


def post_bot(client: RestClient, *, body: dict[str, Any] | None = None) -> Any:
    """Create a new bot

    ``POST /bot``  |  tag: Bot

    Body: CreateBotInput
    Auth: X-CB-KEY  |  Response: BotDto
    """
    return client.request("POST", "/bot", json=body)


def post_bot_ai(client: RestClient, *, body: dict[str, Any] | None = None) -> Any:
    """Create bot with AI

    ``POST /bot/ai``  |  tag: Bot

    Body: AiCreateBotInput
    Auth: X-CB-KEY  |  Response: BotDto
    """
    return client.request("POST", "/bot/ai", json=body)


def get_bot_bbb_templates(client: RestClient) -> Any:
    """Get bot builder builder templates

    ``GET /bot/bbb/templates``  |  tag: Bot

    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    return client.request("GET", "/bot/bbb/templates")


def get_bot_nodedescriptors(client: RestClient) -> Any:
    """Get the node descriptors

    ``GET /bot/nodeDescriptors``  |  tag: Bot

    Body: (none)
    Auth: X-CB-KEY  |  Response: NodeInformation
    """
    return client.request("GET", "/bot/nodeDescriptors")


def delete_bot_id(client: RestClient, id: str) -> Any:
    """Delete a bot

    ``DELETE /bot/{id}``  |  tag: Bot

    Path params:
      - ``id``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/bot/{id}".format(**{"id": id})
    return client.request("DELETE", path)


def get_bot_id(client: RestClient, id: str) -> Any:
    """Get a bot

    ``GET /bot/{id}``  |  tag: Bot

    Path params:
      - ``id``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: BotDto
    """
    path = "/bot/{id}".format(**{"id": id})
    return client.request("GET", path)


def put_bot_id(client: RestClient, id: str, *, body: dict[str, Any] | None = None) -> Any:
    """Update a bot

    ``PUT /bot/{id}``  |  tag: Bot

    Path params:
      - ``id``: str
    Body: UpdateBotInput
    Auth: X-CB-KEY  |  Response: BotDto
    """
    path = "/bot/{id}".format(**{"id": id})
    return client.request("PUT", path, json=body)


def post_bot_id_duplicate(client: RestClient, id: str) -> Any:
    """Duplicate a bot

    ``POST /bot/{id}/duplicate``  |  tag: Bot

    Path params:
      - ``id``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: BotDto
    """
    path = "/bot/{id}/duplicate".format(**{"id": id})
    return client.request("POST", path)


def get_bot_id_export(client: RestClient, id: str, *, botVersion: str | None = None) -> Any:
    """Export a bot

    ``GET /bot/{id}/export``  |  tag: Bot

    Path params:
      - ``id``: str
    Query params:
      - ``botVersion``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: ExportBotResponse
    """
    path = "/bot/{id}/export".format(**{"id": id})
    params = {k: v for k, v in {"botVersion": botVersion}.items() if v is not None}
    return client.request("GET", path, params=params)


def post_bot_id_publish(client: RestClient, id: str) -> Any:
    """Publish a bot

    ``POST /bot/{id}/publish``  |  tag: Bot

    Path params:
      - ``id``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: PublishBotResponse
    """
    path = "/bot/{id}/publish".format(**{"id": id})
    return client.request("POST", path)


def post_bot_id_save(client: RestClient, id: str, *, body: dict[str, Any] | None = None) -> Any:
    """Save a bot

    ``POST /bot/{id}/save``  |  tag: Bot

    Path params:
      - ``id``: str
    Body: SaveBotInput
    Auth: X-CB-KEY  |  Response: SaveBotResponse
    """
    path = "/bot/{id}/save".format(**{"id": id})
    return client.request("POST", path, json=body)


def post_bot_id_savetools(
    client: RestClient,
    id: str,
    *,
    body: dict[str, Any] | None = None,
) -> Any:
    """Save bot tools

    ``POST /bot/{id}/saveTools``  |  tag: Bot

    Path params:
      - ``id``: str
    Body: ToolInputDto
    Auth: X-CB-KEY  |  Response: BotToolDto
    """
    path = "/bot/{id}/saveTools".format(**{"id": id})
    return client.request("POST", path, json=body)


def delete_bot_id_source_sourceid(client: RestClient, id: str, sourceId: str) -> Any:
    """Detach a source from a bot

    ``DELETE /bot/{id}/source/{sourceId}``  |  tag: Bot

    Path params:
      - ``id``: str
      - ``sourceId``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/bot/{id}/source/{sourceId}".format(**{"id": id, "sourceId": sourceId})
    return client.request("DELETE", path)


def post_bot_id_source_sourceid(
    client: RestClient,
    id: str,
    sourceId: str,
    *,
    body: dict[str, Any] | None = None,
) -> Any:
    """Attach a source to a bot

    ``POST /bot/{id}/source/{sourceId}``  |  tag: Bot

    Path params:
      - ``id``: str
      - ``sourceId``: str
    Body: AttachSourceInput
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/bot/{id}/source/{sourceId}".format(**{"id": id, "sourceId": sourceId})
    return client.request("POST", path, json=body)


def get_bot_id_steps(client: RestClient, id: str, *, botVersion: str | None = None) -> Any:
    """Get steps for a version

    ``GET /bot/{id}/steps``  |  tag: Bot

    Path params:
      - ``id``: str
    Query params:
      - ``botVersion``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/bot/{id}/steps".format(**{"id": id})
    params = {k: v for k, v in {"botVersion": botVersion}.items() if v is not None}
    return client.request("GET", path, params=params)


def put_bot_id_version_version(
    client: RestClient,
    id: str,
    version: str,
    *,
    body: dict[str, Any] | None = None,
) -> Any:
    """Update a bot version

    ``PUT /bot/{id}/version/{version}``  |  tag: Bot

    Path params:
      - ``id``: str
      - ``version``: str
    Body: UpdateVersionInput
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/bot/{id}/version/{version}".format(**{"id": id, "version": version})
    return client.request("PUT", path, json=body)
