# @generated by scripts/codegen.py -- DO NOT EDIT.
# Source: schema/endpoints.index.json + schema/openapi.json
#         (vendored from Bleupreneur/closebot-agency-toolkit, MIT).
# Regenerate: python scripts/codegen.py
"""BotSourceVariable endpoints -- generated Closebot operations.

Tag: BotSourceVariable. 2 operation(s). Each function takes a
:class:`~closewire_client.rest.RestClient` as its first argument and delegates
to :meth:`RestClient.request` -- the single paced, authenticated call-site.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover - typing only
    from closewire_client.rest import RestClient

__all__ = [
    "get_botvariables_botid_sourceid",
    "post_botvariables_botid_sourceid",
]


def get_botvariables_botid_sourceid(client: RestClient, botId: str, sourceId: str) -> Any:
    """Get source variables

    ``GET /botVariables/{botId}/{sourceId}``  |  tag: BotSourceVariable

    Path params:
      - ``botId``: str
      - ``sourceId``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: BotVariableDto
    """
    path = "/botVariables/{botId}/{sourceId}".format(**{"botId": botId, "sourceId": sourceId})
    return client.request("GET", path)


def post_botvariables_botid_sourceid(
    client: RestClient,
    botId: str,
    sourceId: str,
    *,
    body: dict[str, Any] | None = None,
) -> Any:
    """Update a source variable

    ``POST /botVariables/{botId}/{sourceId}``  |  tag: BotSourceVariable

    Path params:
      - ``botId``: str
      - ``sourceId``: str
    Body: BotVariableUpdateInput
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/botVariables/{botId}/{sourceId}".format(**{"botId": botId, "sourceId": sourceId})
    return client.request("POST", path, json=body)
