# @generated by scripts/codegen.py -- DO NOT EDIT.
# Source: schema/endpoints.index.json + schema/openapi.json
#         (vendored from Bleupreneur/closebot-agency-toolkit, MIT).
# Regenerate: python scripts/codegen.py
"""BotMetric endpoints -- generated Closebot operations.

Tag: BotMetric. 14 operation(s). Each function takes a
:class:`~closewire_client.rest.RestClient` as its first argument and delegates
to :meth:`RestClient.request` -- the single paced, authenticated call-site.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover - typing only
    from closewire_client.rest import RestClient

__all__ = [
    "get_botmetric_actioncount",
    "get_botmetric_actions",
    "get_botmetric_agencymetric",
    "get_botmetric_agencysummary",
    "get_botmetric_bookinggraph",
    "get_botmetric_leaderboard",
    "get_botmetric_localleaderboard",
    "get_botmetric_logs",
    "get_botmetric_messagecount",
    "get_botmetric_messagefeedback",
    "post_botmetric_messagefeedback",
    "get_botmetric_messagelikes",
    "get_botmetric_messagereason",
    "get_botmetric_messages",
]


def get_botmetric_actioncount(
    client: RestClient,
    *,
    leadId: str | None = None,
    sourceId: str | None = None,
    botId: str | None = None,
    start: str | None = None,
    end: str | None = None,
) -> Any:
    """Get action count

    ``GET /botMetric/actionCount``  |  tag: BotMetric

    Query params:
      - ``leadId``: str
      - ``sourceId``: str
      - ``botId``: str
      - ``start``: str
      - ``end``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    params = {k: v for k, v in {"leadId": leadId, "sourceId": sourceId, "botId": botId, "start": start, "end": end}.items() if v is not None}
    return client.request("GET", "/botMetric/actionCount", params=params)


def get_botmetric_actions(
    client: RestClient,
    *,
    leadId: str | None = None,
    sourceId: str | None = None,
    botId: str | None = None,
    start: str | None = None,
    end: str | None = None,
    maxCount: int | None = None,
) -> Any:
    """Get actions

    ``GET /botMetric/actions``  |  tag: BotMetric

    Query params:
      - ``leadId``: str
      - ``sourceId``: str
      - ``botId``: str
      - ``start``: str
      - ``end``: str
      - ``maxCount``: int
    Body: (none)
    Auth: X-CB-KEY  |  Response: BotMetricAction
    """
    params = {k: v for k, v in {"leadId": leadId, "sourceId": sourceId, "botId": botId, "start": start, "end": end, "maxCount": maxCount}.items() if v is not None}
    return client.request("GET", "/botMetric/actions", params=params)


def get_botmetric_agencymetric(
    client: RestClient,
    *,
    metric: str | None = None,
    start: str | None = None,
    end: str | None = None,
    resolution: str | None = None,
    sourceId: str | None = None,
) -> Any:
    """Get agency metric

    ``GET /botMetric/agencyMetric``  |  tag: BotMetric

    Query params:
      - ``metric``: str
      - ``start``: str
      - ``end``: str
      - ``resolution``: str
      - ``sourceId``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    params = {k: v for k, v in {"metric": metric, "start": start, "end": end, "resolution": resolution, "sourceId": sourceId}.items() if v is not None}
    return client.request("GET", "/botMetric/agencyMetric", params=params)


def get_botmetric_agencysummary(client: RestClient, *, sourceId: str | None = None) -> Any:
    """Get agency summary

    ``GET /botMetric/agencySummary``  |  tag: BotMetric

    Query params:
      - ``sourceId``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: AgencyDashboardSummaryResponse
    """
    params = {k: v for k, v in {"sourceId": sourceId}.items() if v is not None}
    return client.request("GET", "/botMetric/agencySummary", params=params)


def get_botmetric_bookinggraph(
    client: RestClient,
    *,
    start: str | None = None,
    end: str | None = None,
    resolution: str | None = None,
    sourceId: str | None = None,
) -> Any:
    """Get booking graph

    ``GET /botMetric/bookingGraph``  |  tag: BotMetric

    Query params:
      - ``start``: str
      - ``end``: str
      - ``resolution``: str
      - ``sourceId``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    params = {k: v for k, v in {"start": start, "end": end, "resolution": resolution, "sourceId": sourceId}.items() if v is not None}
    return client.request("GET", "/botMetric/bookingGraph", params=params)


def get_botmetric_leaderboard(
    client: RestClient,
    *,
    metric: str | None = None,
    start: str | None = None,
    end: str | None = None,
    numTopLeaders: int | None = None,
) -> Any:
    """Get global leaderboard

    ``GET /botMetric/leaderboard``  |  tag: BotMetric

    Query params:
      - ``metric``: str
      - ``start``: str
      - ``end``: str
      - ``numTopLeaders``: int
    Body: (none)
    Auth: X-CB-KEY  |  Response: LeaderboardResponse
    """
    params = {k: v for k, v in {"metric": metric, "start": start, "end": end, "numTopLeaders": numTopLeaders}.items() if v is not None}
    return client.request("GET", "/botMetric/leaderboard", params=params)


def get_botmetric_localleaderboard(
    client: RestClient,
    *,
    metric: str | None = None,
    start: str | None = None,
    end: str | None = None,
    numSurroundingAgencies: int | None = None,
) -> Any:
    """Get local leaderboard

    ``GET /botMetric/localleaderboard``  |  tag: BotMetric

    Query params:
      - ``metric``: str
      - ``start``: str
      - ``end``: str
      - ``numSurroundingAgencies``: int
    Body: (none)
    Auth: X-CB-KEY  |  Response: LeaderboardResponse
    """
    params = {k: v for k, v in {"metric": metric, "start": start, "end": end, "numSurroundingAgencies": numSurroundingAgencies}.items() if v is not None}
    return client.request("GET", "/botMetric/localleaderboard", params=params)


def get_botmetric_logs(
    client: RestClient,
    *,
    botId: str | None = None,
    messageId: str | None = None,
    sourceId: str | None = None,
    leadId: str | None = None,
    actionId: str | None = None,
    start: str | None = None,
    end: str | None = None,
    maxCount: int | None = None,
) -> Any:
    """Get logs

    ``GET /botMetric/logs``  |  tag: BotMetric

    Query params:
      - ``botId``: str
      - ``messageId``: str
      - ``sourceId``: str
      - ``leadId``: str
      - ``actionId``: str
      - ``start``: str
      - ``end``: str
      - ``maxCount``: int
    Body: (none)
    Auth: X-CB-KEY  |  Response: BotMetricLog
    """
    params = {k: v for k, v in {"botId": botId, "messageId": messageId, "sourceId": sourceId, "leadId": leadId, "actionId": actionId, "start": start, "end": end, "maxCount": maxCount}.items() if v is not None}
    return client.request("GET", "/botMetric/logs", params=params)


def get_botmetric_messagecount(
    client: RestClient,
    *,
    sourceId: str | None = None,
    leadId: str | None = None,
    start: str | None = None,
    end: str | None = None,
) -> Any:
    """Get message count

    ``GET /botMetric/messageCount``  |  tag: BotMetric

    Query params:
      - ``sourceId``: str
      - ``leadId``: str
      - ``start``: str
      - ``end``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    params = {k: v for k, v in {"sourceId": sourceId, "leadId": leadId, "start": start, "end": end}.items() if v is not None}
    return client.request("GET", "/botMetric/messageCount", params=params)


def get_botmetric_messagefeedback(client: RestClient, *, leadId: str | None = None) -> Any:
    """Get messages with feedback

    ``GET /botMetric/messageFeedback``  |  tag: BotMetric

    Query params:
      - ``leadId``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: MessageFeedbackResponse
    """
    params = {k: v for k, v in {"leadId": leadId}.items() if v is not None}
    return client.request("GET", "/botMetric/messageFeedback", params=params)


def post_botmetric_messagefeedback(
    client: RestClient,
    *,
    body: dict[str, Any] | None = None,
) -> Any:
    """Save message feedback

    ``POST /botMetric/messageFeedback``  |  tag: BotMetric

    Body: MessageFeedbackRequest
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    return client.request("POST", "/botMetric/messageFeedback", json=body)


def get_botmetric_messagelikes(client: RestClient, *, leadId: str | None = None) -> Any:
    """Get messages with likes

    ``GET /botMetric/messageLikes``  |  tag: BotMetric

    Query params:
      - ``leadId``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: MessageLikesResponse
    """
    params = {k: v for k, v in {"leadId": leadId}.items() if v is not None}
    return client.request("GET", "/botMetric/messageLikes", params=params)


def get_botmetric_messagereason(client: RestClient, *, messageId: str | None = None) -> Any:
    """Get message feedback reason

    ``GET /botMetric/messageReason``  |  tag: BotMetric

    Query params:
      - ``messageId``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: MessageReason
    """
    params = {k: v for k, v in {"messageId": messageId}.items() if v is not None}
    return client.request("GET", "/botMetric/messageReason", params=params)


def get_botmetric_messages(
    client: RestClient,
    *,
    sourceId: str | None = None,
    leadId: str | None = None,
    start: str | None = None,
    end: str | None = None,
    maxCount: int | None = None,
) -> Any:
    """Get messages

    ``GET /botMetric/messages``  |  tag: BotMetric

    Query params:
      - ``sourceId``: str
      - ``leadId``: str
      - ``start``: str
      - ``end``: str
      - ``maxCount``: int
    Body: (none)
    Auth: X-CB-KEY  |  Response: BotMetricMessage
    """
    params = {k: v for k, v in {"sourceId": sourceId, "leadId": leadId, "start": start, "end": end, "maxCount": maxCount}.items() if v is not None}
    return client.request("GET", "/botMetric/messages", params=params)
