# @generated by scripts/codegen.py -- DO NOT EDIT.
# Source: schema/endpoints.index.json + schema/openapi.json
#         (vendored from Bleupreneur/closebot-agency-toolkit, MIT).
# Regenerate: python scripts/codegen.py
"""BotTemplate endpoints -- generated Closebot operations.

Tag: BotTemplate. 1 operation(s). Each function takes a
:class:`~closewire_client.rest.RestClient` as its first argument and delegates
to :meth:`RestClient.request` -- the single paced, authenticated call-site.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover - typing only
    from closewire_client.rest import RestClient

__all__ = [
    "get_bottemplates",
]


def get_bottemplates(client: RestClient) -> Any:
    """List templates

    ``GET /botTemplates``  |  tag: BotTemplate

    Body: (none)
    Auth: X-CB-KEY  |  Response: BotTemplateDto
    """
    return client.request("GET", "/botTemplates")
