# @generated by scripts/codegen.py -- DO NOT EDIT.
# Source: schema/endpoints.index.json + schema/openapi.json
#         (vendored from Bleupreneur/closebot-agency-toolkit, MIT).
# Regenerate: python scripts/codegen.py
"""BotTesting endpoints -- generated Closebot operations.

Tag: BotTesting. 8 operation(s). Each function takes a
:class:`~closewire_client.rest.RestClient` as its first argument and delegates
to :meth:`RestClient.request` -- the single paced, authenticated call-site.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover - typing only
    from closewire_client.rest import RestClient

__all__ = [
    "get_bot_botid_testsession",
    "post_bot_botid_testsession",
    "post_bot_botid_testsession_message",
    "get_bot_botid_testsession_messages_leadid",
    "delete_bot_botid_testsession_leadid",
    "put_bot_botid_testsession_leadid",
    "post_bot_botid_testsession_leadid_force_step",
    "post_bot_botid_testsession_leadid_rollback",
]


def get_bot_botid_testsession(
    client: RestClient,
    botId: str,
    *,
    offset: int | None = None,
    maxCount: int | None = None,
) -> Any:
    """List test sessions

    ``GET /bot/{botId}/testSession``  |  tag: BotTesting

    Path params:
      - ``botId``: str
    Query params:
      - ``offset``: int
      - ``maxCount``: int
    Body: (none)
    Auth: X-CB-KEY  |  Response: ListLeadDto
    """
    path = "/bot/{botId}/testSession".format(**{"botId": botId})
    params = {k: v for k, v in {"offset": offset, "maxCount": maxCount}.items() if v is not None}
    return client.request("GET", path, params=params)


def post_bot_botid_testsession(client: RestClient, botId: str) -> Any:
    """Create a test session

    ``POST /bot/{botId}/testSession``  |  tag: BotTesting

    Path params:
      - ``botId``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: TestSession
    """
    path = "/bot/{botId}/testSession".format(**{"botId": botId})
    return client.request("POST", path)


def post_bot_botid_testsession_message(
    client: RestClient,
    botId: str,
    *,
    body: dict[str, Any] | None = None,
) -> Any:
    """Send a message to a test session

    ``POST /bot/{botId}/testSession/message``  |  tag: BotTesting

    Path params:
      - ``botId``: str
    Body: TestSessionMessageInput
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/bot/{botId}/testSession/message".format(**{"botId": botId})
    return client.request("POST", path, json=body)


def get_bot_botid_testsession_messages_leadid(
    client: RestClient,
    botId: str,
    leadId: str,
) -> Any:
    """Listen for messages

    ``GET /bot/{botId}/testSession/messages/{leadId}``  |  tag: BotTesting

    Path params:
      - ``botId``: str
      - ``leadId``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/bot/{botId}/testSession/messages/{leadId}".format(**{"botId": botId, "leadId": leadId})
    return client.request("GET", path)


def delete_bot_botid_testsession_leadid(client: RestClient, botId: str, leadId: str) -> Any:
    """Delete a test session

    ``DELETE /bot/{botId}/testSession/{leadId}``  |  tag: BotTesting

    Path params:
      - ``botId``: str
      - ``leadId``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/bot/{botId}/testSession/{leadId}".format(**{"botId": botId, "leadId": leadId})
    return client.request("DELETE", path)


def put_bot_botid_testsession_leadid(
    client: RestClient,
    leadId: str,
    botId: str,
    *,
    body: dict[str, Any] | None = None,
) -> Any:
    """Update a test session

    ``PUT /bot/{botId}/testSession/{leadId}``  |  tag: BotTesting

    Path params:
      - ``leadId``: str
      - ``botId``: str
    Body: UpdateSessionInput
    Auth: X-CB-KEY  |  Response: UpdateSessionDto
    """
    path = "/bot/{botId}/testSession/{leadId}".format(**{"leadId": leadId, "botId": botId})
    return client.request("PUT", path, json=body)


def post_bot_botid_testsession_leadid_force_step(
    client: RestClient,
    leadId: str,
    botId: str,
) -> Any:
    """Force processing

    ``POST /bot/{botId}/testSession/{leadId}/force-step``  |  tag: BotTesting

    Path params:
      - ``leadId``: str
      - ``botId``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/bot/{botId}/testSession/{leadId}/force-step".format(**{"leadId": leadId, "botId": botId})
    return client.request("POST", path)


def post_bot_botid_testsession_leadid_rollback(
    client: RestClient,
    leadId: str,
    botId: str,
    *,
    body: dict[str, Any] | None = None,
) -> Any:
    """Rollback a test session

    ``POST /bot/{botId}/testSession/{leadId}/rollback``  |  tag: BotTesting

    Path params:
      - ``leadId``: str
      - ``botId``: str
    Body: BotTestingRollbackInput
    Auth: X-CB-KEY  |  Response: BotTestingRollbackOutput
    """
    path = "/bot/{botId}/testSession/{leadId}/rollback".format(**{"leadId": leadId, "botId": botId})
    return client.request("POST", path, json=body)
