# @generated by scripts/codegen.py -- DO NOT EDIT.
# Source: schema/endpoints.index.json + schema/openapi.json
#         (vendored from Bleupreneur/closebot-agency-toolkit, MIT).
# Regenerate: python scripts/codegen.py
"""Hierarchy endpoints -- generated Closebot operations.

Tag: Hierarchy. 5 operation(s). Each function takes a
:class:`~closewire_client.rest.RestClient` as its first argument and delegates
to :meth:`RestClient.request` -- the single paced, authenticated call-site.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover - typing only
    from closewire_client.rest import RestClient

__all__ = [
    "get_hierarchy",
    "post_hierarchy",
    "delete_hierarchy_id",
    "get_hierarchy_id",
    "put_hierarchy_id",
]


def get_hierarchy(client: RestClient) -> Any:
    """List folders

    ``GET /hierarchy``  |  tag: Hierarchy

    Body: (none)
    Auth: X-CB-KEY  |  Response: ListHierarchyResult
    """
    return client.request("GET", "/hierarchy")


def post_hierarchy(client: RestClient, *, body: dict[str, Any] | None = None) -> Any:
    """Add a folder

    ``POST /hierarchy``  |  tag: Hierarchy

    Body: AddHierarchyInput
    Auth: X-CB-KEY  |  Response: AddHierarchyOutput
    """
    return client.request("POST", "/hierarchy", json=body)


def delete_hierarchy_id(client: RestClient, id: str) -> Any:
    """Delete a folder

    ``DELETE /hierarchy/{id}``  |  tag: Hierarchy

    Path params:
      - ``id``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/hierarchy/{id}".format(**{"id": id})
    return client.request("DELETE", path)


def get_hierarchy_id(client: RestClient, id: str) -> Any:
    """Get a folder

    ``GET /hierarchy/{id}``  |  tag: Hierarchy

    Path params:
      - ``id``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: ListHierarchyResult
    """
    path = "/hierarchy/{id}".format(**{"id": id})
    return client.request("GET", path)


def put_hierarchy_id(client: RestClient, id: str, *, body: dict[str, Any] | None = None) -> Any:
    """Update a folder

    ``PUT /hierarchy/{id}``  |  tag: Hierarchy

    Path params:
      - ``id``: str
    Body: HierarchyInput
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/hierarchy/{id}".format(**{"id": id})
    return client.request("PUT", path, json=body)
