# @generated by scripts/codegen.py -- DO NOT EDIT.
# Source: schema/endpoints.index.json + schema/openapi.json
#         (vendored from Bleupreneur/closebot-agency-toolkit, MIT).
# Regenerate: python scripts/codegen.py
"""Lead endpoints -- generated Closebot operations.

Tag: Lead. 11 operation(s). Each function takes a
:class:`~closewire_client.rest.RestClient` as its first argument and delegates
to :meth:`RestClient.request` -- the single paced, authenticated call-site.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover - typing only
    from closewire_client.rest import RestClient

__all__ = [
    "get_lead",
    "post_lead_search",
    "delete_lead_leadid",
    "get_lead_leadid",
    "put_lead_leadid",
    "get_lead_leadid_ai_toggle",
    "put_lead_leadid_ai_toggle",
    "put_lead_leadid_instance_botid",
    "get_lead_leadid_page_history",
    "post_lead_leadid_send_message",
    "post_lead_leadid_typing",
]


def get_lead(
    client: RestClient,
    *,
    page: int | None = None,
    pageSize: int | None = None,
    sourceId: str | None = None,
    leadId: str | None = None,
) -> Any:
    """List leads

    ``GET /lead``  |  tag: Lead

    Query params:
      - ``page``: int
      - ``pageSize``: int
      - ``sourceId``: str
      - ``leadId``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: LeadDtoPaginated
    """
    params = {k: v for k, v in {"page": page, "pageSize": pageSize, "sourceId": sourceId, "leadId": leadId}.items() if v is not None}
    return client.request("GET", "/lead", params=params)


def post_lead_search(client: RestClient, *, body: dict[str, Any] | None = None) -> Any:
    """Search leads

    ``POST /lead/search``  |  tag: Lead

    Body: SearchQueryInput
    Auth: X-CB-KEY  |  Response: SearchLeadResultDto
    """
    return client.request("POST", "/lead/search", json=body)


def delete_lead_leadid(client: RestClient, leadId: str) -> Any:
    """Delete a lead

    ``DELETE /lead/{leadId}``  |  tag: Lead

    Path params:
      - ``leadId``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/lead/{leadId}".format(**{"leadId": leadId})
    return client.request("DELETE", path)


def get_lead_leadid(
    client: RestClient,
    leadId: str,
    *,
    includeExternal: bool | None = None,
) -> Any:
    """Get a lead

    ``GET /lead/{leadId}``  |  tag: Lead

    Path params:
      - ``leadId``: str
    Query params:
      - ``includeExternal``: bool
    Body: (none)
    Auth: X-CB-KEY  |  Response: LeadDto
    """
    path = "/lead/{leadId}".format(**{"leadId": leadId})
    params = {k: v for k, v in {"includeExternal": includeExternal}.items() if v is not None}
    return client.request("GET", path, params=params)


def put_lead_leadid(
    client: RestClient,
    leadId: str,
    *,
    body: dict[str, Any] | None = None,
) -> Any:
    """Update lead fields

    ``PUT /lead/{leadId}``  |  tag: Lead

    Path params:
      - ``leadId``: str
    Body: LeadUpdateDto
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/lead/{leadId}".format(**{"leadId": leadId})
    return client.request("PUT", path, json=body)


def get_lead_leadid_ai_toggle(client: RestClient, leadId: str) -> Any:
    """GET /lead/{leadId}/ai-toggle

    ``GET /lead/{leadId}/ai-toggle``  |  tag: Lead

    Path params:
      - ``leadId``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: LeadAiToggleDto
    """
    path = "/lead/{leadId}/ai-toggle".format(**{"leadId": leadId})
    return client.request("GET", path)


def put_lead_leadid_ai_toggle(
    client: RestClient,
    leadId: str,
    *,
    body: dict[str, Any] | None = None,
) -> Any:
    """PUT /lead/{leadId}/ai-toggle

    ``PUT /lead/{leadId}/ai-toggle``  |  tag: Lead

    Path params:
      - ``leadId``: str
    Body: LeadAiToggleUpdateDto
    Auth: X-CB-KEY  |  Response: LeadAiToggleDto
    """
    path = "/lead/{leadId}/ai-toggle".format(**{"leadId": leadId})
    return client.request("PUT", path, json=body)


def put_lead_leadid_instance_botid(
    client: RestClient,
    leadId: str,
    botId: str,
    *,
    body: dict[str, Any] | None = None,
) -> Any:
    """Update a lead instance

    ``PUT /lead/{leadId}/instance/{botId}``  |  tag: Lead

    Path params:
      - ``leadId``: str
      - ``botId``: str
    Body: InstanceUpdateDto
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/lead/{leadId}/instance/{botId}".format(**{"leadId": leadId, "botId": botId})
    return client.request("PUT", path, json=body)


def get_lead_leadid_page_history(
    client: RestClient,
    leadId: str,
    *,
    limit: int | None = None,
) -> Any:
    """GET /lead/{leadId}/page-history

    ``GET /lead/{leadId}/page-history``  |  tag: Lead

    Path params:
      - ``leadId``: str
    Query params:
      - ``limit``: int
    Body: (none)
    Auth: X-CB-KEY  |  Response: LeadPageVisitDto
    """
    path = "/lead/{leadId}/page-history".format(**{"leadId": leadId})
    params = {k: v for k, v in {"limit": limit}.items() if v is not None}
    return client.request("GET", path, params=params)


def post_lead_leadid_send_message(
    client: RestClient,
    leadId: str,
    *,
    body: dict[str, Any] | None = None,
) -> Any:
    """Send a message to a lead

    ``POST /lead/{leadId}/send-message``  |  tag: Lead

    Path params:
      - ``leadId``: str
    Body: SendMessageInputDto
    Auth: X-CB-KEY  |  Response: SendMessageResultDto
    """
    path = "/lead/{leadId}/send-message".format(**{"leadId": leadId})
    return client.request("POST", path, json=body)


def post_lead_leadid_typing(
    client: RestClient,
    leadId: str,
    *,
    body: dict[str, Any] | None = None,
) -> Any:
    """Broadcast human typing state to live subscribers for a lead.

    ``POST /lead/{leadId}/typing``  |  tag: Lead

    Path params:
      - ``leadId``: str
    Body: LeadTypingInputDto
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/lead/{leadId}/typing".format(**{"leadId": leadId})
    return client.request("POST", path, json=body)
