# @generated by scripts/codegen.py -- DO NOT EDIT.
# Source: schema/endpoints.index.json + schema/openapi.json
#         (vendored from Bleupreneur/closebot-agency-toolkit, MIT).
# Regenerate: python scripts/codegen.py
"""Library endpoints -- generated Closebot operations.

Tag: Library. 11 operation(s). Each function takes a
:class:`~closewire_client.rest.RestClient` as its first argument and delegates
to :meth:`RestClient.request` -- the single paced, authenticated call-site.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover - typing only
    from closewire_client.rest import RestClient

__all__ = [
    "get_library_files",
    "post_library_files",
    "delete_library_files_fileid",
    "get_library_files_fileid",
    "put_library_files_fileid",
    "get_library_files_fileid_scrape_pages",
    "put_library_files_fileid_scrape_pages",
    "delete_library_files_fileid_source_sourceid",
    "post_library_files_fileid_source_sourceid",
    "get_library_files_fileid_view",
    "post_library_webscrape",
]


def get_library_files(client: RestClient) -> Any:
    """List files

    ``GET /library/files``  |  tag: Library

    Body: (none)
    Auth: X-CB-KEY  |  Response: FileDto
    """
    return client.request("GET", "/library/files")


def post_library_files(client: RestClient) -> Any:
    """Upload a file

    ``POST /library/files``  |  tag: Library

    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    return client.request("POST", "/library/files")


def delete_library_files_fileid(client: RestClient, fileId: str) -> Any:
    """Delete a file

    ``DELETE /library/files/{fileId}``  |  tag: Library

    Path params:
      - ``fileId``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/library/files/{fileId}".format(**{"fileId": fileId})
    return client.request("DELETE", path)


def get_library_files_fileid(client: RestClient, fileId: str) -> Any:
    """Get a file metadata

    ``GET /library/files/{fileId}``  |  tag: Library

    Path params:
      - ``fileId``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: FileDto
    """
    path = "/library/files/{fileId}".format(**{"fileId": fileId})
    return client.request("GET", path)


def put_library_files_fileid(client: RestClient, fileId: str) -> Any:
    """Replace file content

    ``PUT /library/files/{fileId}``  |  tag: Library

    Path params:
      - ``fileId``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/library/files/{fileId}".format(**{"fileId": fileId})
    return client.request("PUT", path)


def get_library_files_fileid_scrape_pages(client: RestClient, fileId: str) -> Any:
    """Get the scrape pages for a file

    ``GET /library/files/{fileId}/scrape-pages``  |  tag: Library

    Path params:
      - ``fileId``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: WebscrapePageDto
    """
    path = "/library/files/{fileId}/scrape-pages".format(**{"fileId": fileId})
    return client.request("GET", path)


def put_library_files_fileid_scrape_pages(
    client: RestClient,
    fileId: str,
    *,
    body: dict[str, Any] | None = None,
) -> Any:
    """Update the scrape pages for a file

    ``PUT /library/files/{fileId}/scrape-pages``  |  tag: Library

    Path params:
      - ``fileId``: str
    Body: WebscrapePageUpdateDto
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/library/files/{fileId}/scrape-pages".format(**{"fileId": fileId})
    return client.request("PUT", path, json=body)


def delete_library_files_fileid_source_sourceid(
    client: RestClient,
    fileId: str,
    sourceId: str,
) -> Any:
    """Detach a file from a source

    ``DELETE /library/files/{fileId}/source/{sourceId}``  |  tag: Library

    Path params:
      - ``fileId``: str
      - ``sourceId``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/library/files/{fileId}/source/{sourceId}".format(**{"fileId": fileId, "sourceId": sourceId})
    return client.request("DELETE", path)


def post_library_files_fileid_source_sourceid(
    client: RestClient,
    fileId: str,
    sourceId: str,
) -> Any:
    """Attach a file to a source

    ``POST /library/files/{fileId}/source/{sourceId}``  |  tag: Library

    Path params:
      - ``fileId``: str
      - ``sourceId``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/library/files/{fileId}/source/{sourceId}".format(**{"fileId": fileId, "sourceId": sourceId})
    return client.request("POST", path)


def get_library_files_fileid_view(client: RestClient, fileId: str) -> Any:
    """Get file content

    ``GET /library/files/{fileId}/view``  |  tag: Library

    Path params:
      - ``fileId``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/library/files/{fileId}/view".format(**{"fileId": fileId})
    return client.request("GET", path)


def post_library_webscrape(client: RestClient, *, body: dict[str, Any] | None = None) -> Any:
    """Create a Web-Scrape file

    ``POST /library/webscrape``  |  tag: Library

    Body: UploadWebscrapeToSourceInput
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    return client.request("POST", "/library/webscrape", json=body)
