# @generated by scripts/codegen.py -- DO NOT EDIT.
# Source: schema/endpoints.index.json + schema/openapi.json
#         (vendored from Bleupreneur/closebot-agency-toolkit, MIT).
# Regenerate: python scripts/codegen.py
"""LiveDemo endpoints -- generated Closebot operations.

Tag: LiveDemo. 10 operation(s). Each function takes a
:class:`~closewire_client.rest.RestClient` as its first argument and delegates
to :meth:`RestClient.request` -- the single paced, authenticated call-site.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover - typing only
    from closewire_client.rest import RestClient

__all__ = [
    "get_bot_live_demo_live_key",
    "post_bot_live_demo_live_key_session",
    "get_bot_live_demo_live_key_session_sessionleadid",
    "put_bot_live_demo_live_key_session_sessionleadid",
    "post_bot_live_demo_live_key_session_sessionleadid_message",
    "get_bot_live_demo_live_key_session_sessionleadid_stream",
    "get_bot_live_demo_botid",
    "post_bot_live_demo_botid",
    "delete_bot_live_demo_botid_key",
    "put_bot_live_demo_botid_key",
]


def get_bot_live_demo_live_key(client: RestClient, key: str) -> Any:
    """Get Live Demo

    ``GET /bot-live-demo/live/{key}``  |  tag: LiveDemo

    Path params:
      - ``key``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: LiveDemoDto
    """
    path = "/bot-live-demo/live/{key}".format(**{"key": key})
    return client.request("GET", path)


def post_bot_live_demo_live_key_session(client: RestClient, key: str) -> Any:
    """Create Live Demo Session

    ``POST /bot-live-demo/live/{key}/session``  |  tag: LiveDemo

    Path params:
      - ``key``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: LiveDemoSessionDto
    """
    path = "/bot-live-demo/live/{key}/session".format(**{"key": key})
    return client.request("POST", path)


def get_bot_live_demo_live_key_session_sessionleadid(
    client: RestClient,
    key: str,
    sessionLeadId: str,
) -> Any:
    """Get Live Demo Lead

    ``GET /bot-live-demo/live/{key}/session/{sessionLeadId}``  |  tag: LiveDemo

    Path params:
      - ``key``: str
      - ``sessionLeadId``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/bot-live-demo/live/{key}/session/{sessionLeadId}".format(**{"key": key, "sessionLeadId": sessionLeadId})
    return client.request("GET", path)


def put_bot_live_demo_live_key_session_sessionleadid(
    client: RestClient,
    key: str,
    sessionLeadId: str,
    *,
    body: dict[str, Any] | None = None,
) -> Any:
    """Update Live Demo Fields

    ``PUT /bot-live-demo/live/{key}/session/{sessionLeadId}``  |  tag: LiveDemo

    Path params:
      - ``key``: str
      - ``sessionLeadId``: str
    Body: LeadUpdateDto
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/bot-live-demo/live/{key}/session/{sessionLeadId}".format(**{"key": key, "sessionLeadId": sessionLeadId})
    return client.request("PUT", path, json=body)


def post_bot_live_demo_live_key_session_sessionleadid_message(
    client: RestClient,
    key: str,
    sessionLeadId: str,
    *,
    body: dict[str, Any] | None = None,
) -> Any:
    """Stream Live Demo Messages

    ``POST /bot-live-demo/live/{key}/session/{sessionLeadId}/message``  |  tag: LiveDemo

    Path params:
      - ``key``: str
      - ``sessionLeadId``: str
    Body: LiveDemoMessageInput
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/bot-live-demo/live/{key}/session/{sessionLeadId}/message".format(**{"key": key, "sessionLeadId": sessionLeadId})
    return client.request("POST", path, json=body)


def get_bot_live_demo_live_key_session_sessionleadid_stream(
    client: RestClient,
    key: str,
    sessionLeadId: str,
) -> Any:
    """Stream Live Demo Messages

    ``GET /bot-live-demo/live/{key}/session/{sessionLeadId}/stream``  |  tag: LiveDemo

    Path params:
      - ``key``: str
      - ``sessionLeadId``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/bot-live-demo/live/{key}/session/{sessionLeadId}/stream".format(**{"key": key, "sessionLeadId": sessionLeadId})
    return client.request("GET", path)


def get_bot_live_demo_botid(client: RestClient, botId: str) -> Any:
    """List Live Demos

    ``GET /bot-live-demo/{botId}``  |  tag: LiveDemo

    Path params:
      - ``botId``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: LiveDemoDto
    """
    path = "/bot-live-demo/{botId}".format(**{"botId": botId})
    return client.request("GET", path)


def post_bot_live_demo_botid(
    client: RestClient,
    botId: str,
    *,
    body: dict[str, Any] | None = None,
) -> Any:
    """Create Live Demo

    ``POST /bot-live-demo/{botId}``  |  tag: LiveDemo

    Path params:
      - ``botId``: str
    Body: LiveDemoCreateDto
    Auth: X-CB-KEY  |  Response: LiveDemoDto
    """
    path = "/bot-live-demo/{botId}".format(**{"botId": botId})
    return client.request("POST", path, json=body)


def delete_bot_live_demo_botid_key(client: RestClient, botId: str, key: str) -> Any:
    """Delete Live Demo

    ``DELETE /bot-live-demo/{botId}/{key}``  |  tag: LiveDemo

    Path params:
      - ``botId``: str
      - ``key``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: LiveDemoDto
    """
    path = "/bot-live-demo/{botId}/{key}".format(**{"botId": botId, "key": key})
    return client.request("DELETE", path)


def put_bot_live_demo_botid_key(
    client: RestClient,
    botId: str,
    key: str,
    *,
    body: dict[str, Any] | None = None,
) -> Any:
    """Update Live Demo

    ``PUT /bot-live-demo/{botId}/{key}``  |  tag: LiveDemo

    Path params:
      - ``botId``: str
      - ``key``: str
    Body: LiveDemoCreateDto
    Auth: X-CB-KEY  |  Response: LiveDemoDto
    """
    path = "/bot-live-demo/{botId}/{key}".format(**{"botId": botId, "key": key})
    return client.request("PUT", path, json=body)
