# @generated by scripts/codegen.py -- DO NOT EDIT.
# Source: schema/endpoints.index.json + schema/openapi.json
#         (vendored from Bleupreneur/closebot-agency-toolkit, MIT).
# Regenerate: python scripts/codegen.py
"""Notification endpoints -- generated Closebot operations.

Tag: Notification. 5 operation(s). Each function takes a
:class:`~closewire_client.rest.RestClient` as its first argument and delegates
to :meth:`RestClient.request` -- the single paced, authenticated call-site.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover - typing only
    from closewire_client.rest import RestClient

__all__ = [
    "get_notifications",
    "get_notifications_forwarding",
    "put_notifications_forwarding",
    "delete_notifications_id",
    "put_notifications_id",
]


def get_notifications(client: RestClient) -> Any:
    """List notifications

    ``GET /notifications``  |  tag: Notification

    Body: (none)
    Auth: X-CB-KEY  |  Response: NotificationDto
    """
    return client.request("GET", "/notifications")


def get_notifications_forwarding(client: RestClient) -> Any:
    """Get notification forwarding settings

    ``GET /notifications/forwarding``  |  tag: Notification

    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    return client.request("GET", "/notifications/forwarding")


def put_notifications_forwarding(
    client: RestClient,
    *,
    body: dict[str, Any] | None = None,
) -> Any:
    """Update notification forwarding settings

    ``PUT /notifications/forwarding``  |  tag: Notification

    Body: NotificationForwardingDto
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    return client.request("PUT", "/notifications/forwarding", json=body)


def delete_notifications_id(client: RestClient, id: str) -> Any:
    """Delete a notification

    ``DELETE /notifications/{id}``  |  tag: Notification

    Path params:
      - ``id``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: NotificationDto
    """
    path = "/notifications/{id}".format(**{"id": id})
    return client.request("DELETE", path)


def put_notifications_id(
    client: RestClient,
    id: str,
    *,
    body: dict[str, Any] | None = None,
) -> Any:
    """Update a notification

    ``PUT /notifications/{id}``  |  tag: Notification

    Path params:
      - ``id``: str
    Body: NotificationUpdateDto
    Auth: X-CB-KEY  |  Response: NotificationDto
    """
    path = "/notifications/{id}".format(**{"id": id})
    return client.request("PUT", path, json=body)
