# @generated by scripts/codegen.py -- DO NOT EDIT.
# Source: schema/endpoints.index.json + schema/openapi.json
#         (vendored from Bleupreneur/closebot-agency-toolkit, MIT).
# Regenerate: python scripts/codegen.py
"""Persona endpoints -- generated Closebot operations.

Tag: Persona. 5 operation(s). Each function takes a
:class:`~closewire_client.rest.RestClient` as its first argument and delegates
to :meth:`RestClient.request` -- the single paced, authenticated call-site.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover - typing only
    from closewire_client.rest import RestClient

__all__ = [
    "get_persona",
    "post_persona",
    "delete_persona_id",
    "get_persona_id",
    "put_persona_id",
]


def get_persona(client: RestClient) -> Any:
    """List personas

    ``GET /persona``  |  tag: Persona

    Body: (none)
    Auth: X-CB-KEY  |  Response: PersonaDto
    """
    return client.request("GET", "/persona")


def post_persona(client: RestClient, *, body: dict[str, Any] | None = None) -> Any:
    """Create a new persona

    ``POST /persona``  |  tag: Persona

    Body: CreatePersonaInput
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    return client.request("POST", "/persona", json=body)


def delete_persona_id(client: RestClient, id: str) -> Any:
    """Delete a persona

    ``DELETE /persona/{id}``  |  tag: Persona

    Path params:
      - ``id``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/persona/{id}".format(**{"id": id})
    return client.request("DELETE", path)


def get_persona_id(client: RestClient, id: str) -> Any:
    """Get a persona

    ``GET /persona/{id}``  |  tag: Persona

    Path params:
      - ``id``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: PersonaDto
    """
    path = "/persona/{id}".format(**{"id": id})
    return client.request("GET", path)


def put_persona_id(client: RestClient, id: str, *, body: dict[str, Any] | None = None) -> Any:
    """Update a persona

    ``PUT /persona/{id}``  |  tag: Persona

    Path params:
      - ``id``: str
    Body: UpdatePersonaInput
    Auth: X-CB-KEY  |  Response: PersonaDto
    """
    path = "/persona/{id}".format(**{"id": id})
    return client.request("PUT", path, json=body)
