# @generated by scripts/codegen.py -- DO NOT EDIT.
# Source: schema/endpoints.index.json + schema/openapi.json
#         (vendored from Bleupreneur/closebot-agency-toolkit, MIT).
# Regenerate: python scripts/codegen.py
"""SmartFAQ endpoints -- generated Closebot operations.

Tag: SmartFAQ. 5 operation(s). Each function takes a
:class:`~closewire_client.rest.RestClient` as its first argument and delegates
to :meth:`RestClient.request` -- the single paced, authenticated call-site.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover - typing only
    from closewire_client.rest import RestClient

__all__ = [
    "get_smart_faq",
    "post_smart_faq",
    "post_smart_faq_answer",
    "post_smart_faq_answered_followup",
    "delete_smart_faq_id",
]


def get_smart_faq(
    client: RestClient,
    *,
    sourceId: str | None = None,
    state: str | None = None,
    answered: str | None = None,
) -> Any:
    """List FAQs

    ``GET /smart-faq``  |  tag: SmartFAQ

    Query params:
      - ``sourceId``: str
      - ``state``: str
      - ``answered``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: SmartFAQDto
    """
    params = {k: v for k, v in {"sourceId": sourceId, "state": state, "answered": answered}.items() if v is not None}
    return client.request("GET", "/smart-faq", params=params)


def post_smart_faq(client: RestClient, *, body: dict[str, Any] | None = None) -> Any:
    """Create a new FAQ

    ``POST /smart-faq``  |  tag: SmartFAQ

    Body: CreateSmartFAQRequest
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    return client.request("POST", "/smart-faq", json=body)


def post_smart_faq_answer(client: RestClient, *, body: dict[str, Any] | None = None) -> Any:
    """Answer multiple FAQs

    ``POST /smart-faq/answer``  |  tag: SmartFAQ

    Body: AnswerMultipleFAQsRequest
    Auth: X-CB-KEY  |  Response: SmartFAQDto
    """
    return client.request("POST", "/smart-faq/answer", json=body)


def post_smart_faq_answered_followup(
    client: RestClient,
    *,
    body: dict[str, Any] | None = None,
) -> Any:
    """Follow up on answered FAQs

    ``POST /smart-faq/answered-followup``  |  tag: SmartFAQ

    Body: AnsweredFAQFollowUpRequest
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    return client.request("POST", "/smart-faq/answered-followup", json=body)


def delete_smart_faq_id(client: RestClient, id: str) -> Any:
    """Delete an FAQ

    ``DELETE /smart-faq/{id}``  |  tag: SmartFAQ

    Path params:
      - ``id``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/smart-faq/{id}".format(**{"id": id})
    return client.request("DELETE", path)
