# @generated by scripts/codegen.py -- DO NOT EDIT.
# Source: schema/endpoints.index.json + schema/openapi.json
#         (vendored from Bleupreneur/closebot-agency-toolkit, MIT).
# Regenerate: python scripts/codegen.py
"""Source endpoints -- generated Closebot operations.

Tag: Source. 10 operation(s). Each function takes a
:class:`~closewire_client.rest.RestClient` as its first argument and delegates
to :meth:`RestClient.request` -- the single paced, authenticated call-site.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover - typing only
    from closewire_client.rest import RestClient

__all__ = [
    "get_agency_source",
    "post_agency_source",
    "delete_agency_source_id",
    "get_a_source",
    "get_agency_source_id_calendars",
    "get_agency_source_id_channels",
    "get_agency_source_id_fields",
    "get_agency_source_id_owners",
    "get_agency_source_id_tags",
    "put_agency_source_sourceid",
]


def get_agency_source(
    client: RestClient,
    *,
    pageSize: int | None = None,
    page: int | None = None,
    query: str | None = None,
    category: str | None = None,
    order: str | None = None,
    forceTokenRefresh: bool | None = None,
) -> Any:
    """List sources

    ``GET /agency/source``  |  tag: Source

    Query params:
      - ``pageSize``: int
      - ``page``: int
      - ``query``: str
      - ``category``: str
      - ``order``: str
      - ``forceTokenRefresh``: bool
    Body: (none)
    Auth: X-CB-KEY  |  Response: SourceDtoPaginated
    """
    params = {k: v for k, v in {"pageSize": pageSize, "page": page, "query": query, "category": category, "order": order, "forceTokenRefresh": forceTokenRefresh}.items() if v is not None}
    return client.request("GET", "/agency/source", params=params)


def post_agency_source(client: RestClient, *, body: dict[str, Any] | None = None) -> Any:
    """Add a source

    ``POST /agency/source``  |  tag: Source

    Body: AddSourceInput
    Auth: X-CB-KEY  |  Response: SourceDto
    """
    return client.request("POST", "/agency/source", json=body)


def delete_agency_source_id(client: RestClient, id: str) -> Any:
    """Delete a source

    ``DELETE /agency/source/{id}``  |  tag: Source

    Path params:
      - ``id``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/agency/source/{id}".format(**{"id": id})
    return client.request("DELETE", path)


def get_a_source(client: RestClient, id: str) -> Any:
    """Get a source

    ``GET /agency/source/{id}``  |  tag: Source

    Path params:
      - ``id``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: SourceDto
    """
    path = "/agency/source/{id}".format(**{"id": id})
    return client.request("GET", path)


def get_agency_source_id_calendars(client: RestClient, id: str) -> Any:
    """List source calendars

    ``GET /agency/source/{id}/calendars``  |  tag: Source

    Path params:
      - ``id``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: SourceCalendarDto
    """
    path = "/agency/source/{id}/calendars".format(**{"id": id})
    return client.request("GET", path)


def get_agency_source_id_channels(client: RestClient, id: str) -> Any:
    """List source channels

    ``GET /agency/source/{id}/channels``  |  tag: Source

    Path params:
      - ``id``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: SourceChannelDto
    """
    path = "/agency/source/{id}/channels".format(**{"id": id})
    return client.request("GET", path)


def get_agency_source_id_fields(client: RestClient, id: str) -> Any:
    """List source fields

    ``GET /agency/source/{id}/fields``  |  tag: Source

    Path params:
      - ``id``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: SourceFieldCollectionDto
    """
    path = "/agency/source/{id}/fields".format(**{"id": id})
    return client.request("GET", path)


def get_agency_source_id_owners(client: RestClient, id: str) -> Any:
    """List HubSpot owners

    ``GET /agency/source/{id}/owners``  |  tag: Source

    Path params:
      - ``id``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: SourceOwnerDto
    """
    path = "/agency/source/{id}/owners".format(**{"id": id})
    return client.request("GET", path)


def get_agency_source_id_tags(client: RestClient, id: str) -> Any:
    """List source tags

    ``GET /agency/source/{id}/tags``  |  tag: Source

    Path params:
      - ``id``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: SourceTagDto
    """
    path = "/agency/source/{id}/tags".format(**{"id": id})
    return client.request("GET", path)


def put_agency_source_sourceid(
    client: RestClient,
    sourceId: str,
    *,
    body: dict[str, Any] | None = None,
) -> Any:
    """Update a source

    ``PUT /agency/source/{sourceId}``  |  tag: Source

    Path params:
      - ``sourceId``: str
    Body: UpdateSourceInput
    Auth: X-CB-KEY  |  Response: SourceDto
    """
    path = "/agency/source/{sourceId}".format(**{"sourceId": sourceId})
    return client.request("PUT", path, json=body)
