# @generated by scripts/codegen.py -- DO NOT EDIT.
# Source: schema/endpoints.index.json + schema/openapi.json
#         (vendored from Bleupreneur/closebot-agency-toolkit, MIT).
# Regenerate: python scripts/codegen.py
"""Webhook endpoints -- generated Closebot operations.

Tag: Webhook. 1 operation(s). Each function takes a
:class:`~closewire_client.rest.RestClient` as its first argument and delegates
to :meth:`RestClient.request` -- the single paced, authenticated call-site.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover - typing only
    from closewire_client.rest import RestClient

__all__ = [
    "post_webhook_event_sourceid",
]


def post_webhook_event_sourceid(client: RestClient, sourceId: str) -> Any:
    """Send a webhook event

    ``POST /webhook/event/{sourceId}``  |  tag: Webhook

    Path params:
      - ``sourceId``: str
    Body: (none)
    Auth: X-CB-KEY  |  Response: (unspecified)
    """
    path = "/webhook/event/{sourceId}".format(**{"sourceId": sourceId})
    return client.request("POST", path)
