#!/usr/bin/env python3
"""Generate typed endpoint stubs for Closewire from the vendored Closebot spec.

Reads the vendored oracle (``schema/endpoints.index.json`` for operation identity/naming
+ ``schema/openapi.json`` for parameters) and emits one Python function per REST
operation into ``closewire_client/endpoints/<tag>.py`` — file per tag, function per
operation. Bodies are ``raise NotImplementedError``; no HTTP is performed (the generated
functions are wired to :class:`~closewire_client.rest.RestClient` in phase 03).

Also (re)writes ``closewire_client/endpoints/__init__.py`` and the human-facing
``OPERATIONS.md`` index at the repo root.

Design notes
------------
* The raw Swagger omits ``operationId`` on 125/126 operations, so operation **names**
  come from the toolkit index's ``id`` field (globally unique). Parameters come from the
  Swagger (path/query, typed).
* The single live-message operation (``POST /message`` on ``api.closebot.ai``, tag
  ``LiveMessage``) is intentionally skipped — it lives in :mod:`closewire_client.live`.
* Deterministic + idempotent: operations are sorted, no timestamps are embedded, and the
  ``endpoints/`` directory is fully rebuilt each run. Re-running produces byte-identical
  output for the same inputs.

Usage: ``python scripts/codegen.py``
"""

from __future__ import annotations

import json
import keyword
import re
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
SCHEMA_DIR = ROOT / "schema"
ENDPOINTS_DIR = ROOT / "closewire_client" / "endpoints"
OPERATIONS_MD = ROOT / "OPERATIONS.md"

GENERATED_MARKER = "@generated by scripts/codegen.py"

_HTTP_METHODS = ("get", "put", "post", "delete", "patch", "options", "head", "trace")
_TYPE_MAP = {"string": "str", "integer": "int", "number": "float", "boolean": "bool"}
_RESERVED_PARAMS = {"client", "body", "self", "cls"}


# ── Name helpers ──────────────────────────────────────────────────────────────
def tag_to_module(tag: str) -> str:
    """``BotMetric`` -> ``bot_metric``; ``SmartFAQ`` -> ``smart_faq``."""
    s = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", tag)
    s = re.sub(r"(?<=[A-Z])(?=[A-Z][a-z])", "_", s)
    return re.sub(r"[^0-9a-zA-Z]+", "_", s).strip("_").lower()


def op_to_func(op_id: str) -> str:
    """``get_account-apikey`` -> ``get_account_apikey`` (valid, unique identifier)."""
    name = re.sub(r"[^0-9a-zA-Z]+", "_", op_id).strip("_").lower()
    if not name:
        name = "op"
    if name[0].isdigit():
        name = f"op_{name}"
    return name


def safe_param(name: str, used: set[str]) -> str:
    """Turn an OpenAPI parameter name into a unique, non-reserved identifier."""
    ident = re.sub(r"[^0-9a-zA-Z_]+", "_", name).strip("_") or "param"
    if ident[0].isdigit():
        ident = f"p_{ident}"
    while keyword.iskeyword(ident) or ident in _RESERVED_PARAMS or ident in used:
        ident += "_"
    used.add(ident)
    return ident


def py_type(schema_type: str | None) -> str:
    return _TYPE_MAP.get(schema_type or "", "str")


# ── Spec loading ──────────────────────────────────────────────────────────────
def load_inputs() -> tuple[list[dict[str, Any]], dict[tuple[str, str], list[dict[str, Any]]]]:
    """Return (REST index entries, {(METHOD, path): [param dicts]} from the Swagger)."""
    index = json.loads((SCHEMA_DIR / "endpoints.index.json").read_text(encoding="utf-8"))
    spec = json.loads((SCHEMA_DIR / "openapi.json").read_text(encoding="utf-8"))

    rest_entries = [e for e in index if "base_url" not in e]  # drop the live-message op

    params_by_op: dict[tuple[str, str], list[dict[str, Any]]] = {}
    for path, item in spec["paths"].items():
        shared = item.get("parameters", []) or []
        for method, op in item.items():
            if method.lower() not in _HTTP_METHODS:
                continue
            merged = list(shared) + list(op.get("parameters", []) or [])
            params_by_op[(method.upper(), path)] = merged
    return rest_entries, params_by_op


# ── Rendering ─────────────────────────────────────────────────────────────────
def render_function(entry: dict[str, Any], params: list[dict[str, Any]]) -> str:
    func = op_to_func(entry["id"])
    method, path, tag = entry["method"], entry["path"], entry["tag"]
    summary = (entry.get("summary") or "").replace('"""', "'''").strip()
    request_body = entry.get("request_body")
    response = entry.get("response_schema")
    auth = entry.get("auth") or "X-CB-KEY"

    path_params = [p for p in params if p.get("in") == "path"]
    query_params = [p for p in params if p.get("in") == "query"]

    used: set[str] = set(_RESERVED_PARAMS)
    # Preserve original name -> chosen identifier for the signature + docstring.
    path_sig, path_doc = [], []
    for p in path_params:
        ident = safe_param(p["name"], used)
        ptype = py_type((p.get("schema") or {}).get("type"))
        path_sig.append(f"{ident}: {ptype}")
        path_doc.append((p["name"], ident, ptype))

    query_sig, query_doc = [], []
    for p in query_params:
        ident = safe_param(p["name"], used)
        ptype = py_type((p.get("schema") or {}).get("type"))
        required = " (required)" if p.get("required") else ""
        query_sig.append(f"{ident}: {ptype} | None = None")
        query_doc.append((p["name"], ident, ptype, required))

    before = ["client: RestClient", *path_sig]
    after: list[str] = []
    if request_body:
        after.append("body: dict[str, Any] | None = None")
    after.extend(query_sig)

    if after:
        signature = f"def {func}({', '.join(before)}, *, {', '.join(after)}) -> Any:"
    else:
        signature = f"def {func}({', '.join(before)}) -> Any:"

    # Wrap long signatures across lines for readability / line length.
    if len(signature) > 96:
        parts = before + (["*"] if after else []) + after
        joined = ",\n    ".join(parts)
        signature = f"def {func}(\n    {joined},\n) -> Any:"

    # Docstring
    doc: list[str] = [summary or f"{method} {path}"]
    doc.append("")
    doc.append(f"``{method} {path}``  |  tag: {tag}")
    doc.append("")
    if path_doc:
        doc.append("Path params:")
        for orig, ident, ptype in path_doc:
            note = "" if ident == orig else f" (as ``{ident}``)"
            doc.append(f"  - ``{orig}``{note}: {ptype}")
    if query_doc:
        doc.append("Query params:")
        for orig, ident, ptype, required in query_doc:
            note = "" if ident == orig else f" (as ``{ident}``)"
            doc.append(f"  - ``{orig}``{note}: {ptype}{required}")
    doc.append(f"Body: {request_body or '(none)'}")
    doc.append(f"Auth: {auth}  |  Response: {response or '(unspecified)'}")

    doc_block = "\n".join(f"    {line}".rstrip() for line in doc)

    # Body: delegate to the single paced call-site, RestClient.request.
    body_lines: list[str] = []
    if path_doc:
        mapping = ", ".join(f'"{orig}": {ident}' for orig, ident, _ in path_doc)
        body_lines.append(f'path = "{path}".format(**{{{mapping}}})')
        path_expr = "path"
    else:
        path_expr = f'"{path}"'

    call_args = [f'"{method}"', path_expr]
    if query_doc:
        qmap = ", ".join(f'"{orig}": {ident}' for orig, ident, _, _ in query_doc)
        body_lines.append(
            f"params = {{k: v for k, v in {{{qmap}}}.items() if v is not None}}"
        )
        call_args.append("params=params")
    if request_body:
        call_args.append("json=body")

    call = f"return client.request({', '.join(call_args)})"
    if len(f"    {call}") > 96:
        inner = ",\n        ".join(call_args)
        call = f"return client.request(\n        {inner},\n    )"
    body_lines.append(call)
    body = "\n".join(f"    {line}" for line in body_lines)

    return (
        f"{signature}\n"
        f'    """{doc_block[4:]}\n'
        f'    """\n'
        f"{body}\n"
    )


def render_module(tag: str, entries: list[dict[str, Any]], rendered: list[tuple[str, str]]) -> str:
    names = [name for name, _ in rendered]
    all_list = ",\n".join(f'    "{n}"' for n in names)
    bodies = "\n\n".join(text for _, text in rendered)
    header = (
        f"# {GENERATED_MARKER} -- DO NOT EDIT.\n"
        f"# Source: schema/endpoints.index.json + schema/openapi.json\n"
        f"#         (vendored from Bleupreneur/closebot-agency-toolkit, MIT).\n"
        f"# Regenerate: python scripts/codegen.py\n"
    )
    docstring = (
        f'"""{tag} endpoints -- generated Closebot operations.\n\n'
        f"Tag: {tag}. {len(entries)} operation(s). Each function takes a\n"
        f":class:`~closewire_client.rest.RestClient` as its first argument and delegates\n"
        f"to :meth:`RestClient.request` -- the single paced, authenticated call-site.\n"
        f'"""\n'
    )
    imports = (
        "from __future__ import annotations\n\n"
        "from typing import TYPE_CHECKING, Any\n\n"
        "if TYPE_CHECKING:  # pragma: no cover - typing only\n"
        "    from closewire_client.rest import RestClient\n\n"
        f"__all__ = [\n{all_list},\n]\n"
    )
    return f"{header}{docstring}\n{imports}\n\n{bodies}"


def render_init(modules: list[str]) -> str:
    header = (
        f"# {GENERATED_MARKER} -- DO NOT EDIT.\n"
        f"# Regenerate: python scripts/codegen.py\n"
    )
    docstring = (
        '"""Generated Closebot endpoint modules -- one per API tag.\n\n'
        "Each submodule exposes module-level functions (one per operation) that take a\n"
        ":class:`~closewire_client.rest.RestClient`. Operation identity/naming comes from\n"
        "the vendored ``schema/endpoints.index.json``; see ``OPERATIONS.md`` for the full\n"
        'index. The runtime live-message op lives in :mod:`closewire_client.live`.\n"""\n'
    )
    imports = "\n".join(f"from closewire_client.endpoints import {m} as {m}" for m in modules)
    all_list = ",\n".join(f'    "{m}"' for m in modules)
    return f"{header}{docstring}\n{imports}\n\nMODULES = [\n{all_list},\n]\n\n__all__ = list(MODULES)\n"


def render_operations_md(by_tag: dict[str, list[dict[str, Any]]]) -> str:
    total = sum(len(v) for v in by_tag.values())
    lines = [
        "<!-- @generated by scripts/codegen.py -- DO NOT EDIT. Run: python scripts/codegen.py -->",
        "",
        "# Closebot operations",
        "",
        f"**{total} REST operations across {len(by_tag)} tags**, generated from the vendored "
        "spec (`schema/endpoints.index.json` + `schema/openapi.json`).",
        "",
        "The runtime live-message operation (`POST /message`) is documented separately in "
        "`schema/live-message.json` and implemented in `closewire_client/live.py`.",
        "",
    ]
    for tag in sorted(by_tag):
        entries = by_tag[tag]
        module = tag_to_module(tag)
        lines.append(f"## {tag} ({len(entries)})")
        lines.append("")
        lines.append("| Method | Path | Function | Summary |")
        lines.append("| --- | --- | --- | --- |")
        for e in entries:
            func = op_to_func(e["id"])
            summary = (e.get("summary") or "").replace("|", "\\|")
            lines.append(f"| {e['method']} | `{e['path']}` | `{module}.{func}` | {summary} |")
        lines.append("")
    return "\n".join(lines)


# ── Orchestration ─────────────────────────────────────────────────────────────
GENERATED_MARKER = "@generated by scripts/codegen.py"


def clean_endpoints_dir() -> list[str]:
    """Remove only the *generated* ``*.py`` in the endpoints package.

    Hand-written modules live here too (phase 05's curated read client), so a blanket
    wipe would silently delete them on the next spec refresh. Generated files are
    identified by the marker their own header carries; anything without it is left alone.
    """
    removed = []
    for py in sorted(ENDPOINTS_DIR.glob("*.py")):
        try:
            head = py.read_text(encoding="utf-8")[:400]
        except OSError:
            continue
        if GENERATED_MARKER not in head:
            continue  # hand-written — not ours to delete
        py.unlink()
        removed.append(py.name)
    return removed


def main() -> int:
    rest_entries, params_by_op = load_inputs()

    by_tag: dict[str, list[dict[str, Any]]] = {}
    for entry in rest_entries:
        by_tag.setdefault(entry["tag"], []).append(entry)
    # Deterministic ordering: tags alphabetical, ops by (path, method).
    for tag in by_tag:
        by_tag[tag].sort(key=lambda e: (e["path"], e["method"]))

    ENDPOINTS_DIR.mkdir(parents=True, exist_ok=True)
    removed = clean_endpoints_dir()

    modules: list[str] = []
    func_total = 0
    for tag in sorted(by_tag):
        entries = by_tag[tag]
        rendered = [
            (op_to_func(e["id"]), render_function(e, params_by_op.get((e["method"], e["path"]), [])))
            for e in entries
        ]
        module = tag_to_module(tag)
        (ENDPOINTS_DIR / f"{module}.py").write_text(render_module(tag, entries, rendered), encoding="utf-8")
        modules.append(module)
        func_total += len(rendered)

    modules.sort()
    (ENDPOINTS_DIR / "__init__.py").write_text(render_init(modules), encoding="utf-8")
    OPERATIONS_MD.write_text(render_operations_md(by_tag), encoding="utf-8")

    print(f"codegen: removed {len(removed)} old file(s), wrote {len(modules)} tag modules.")
    print(f"codegen: {func_total} operation stubs across {len(by_tag)} tags.")
    print(f"codegen: wrote {OPERATIONS_MD.relative_to(ROOT)} and endpoints/__init__.py.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
